// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kttdqktzsaalrlgiasqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dGRxa3R6c2FhbHJsZ2lhc3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDU4MjMsImV4cCI6MjA2MTA4MTgyM30.kLqI9J-8N_d4nMcahlW5mv3zIBi7mvBLqBpp04syh0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);